baseURL = "https://uthoplatforms.github.io/"
title = "utho Docs"

[[module.imports]]
path = "hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[taxonomies]
category = "categories"
author = "authors"
tag = "tags"

[[menu.main]]
name = "Doc Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Features"
pageRef = "/features"
weight = 3

[[menu.main]]
name = "Contact ↗"
url = "https://github.com/utho"
weight = 5

[[menu.main]]
name = "Search"
weight = 6

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 7
url = "https://uthoplatforms.github.io/docs/"

  [menu.main.params]
  icon = "github"

[[menu.main]]
name = "Twitter"
weight = 8
url = "https://twitter.com/"

  [menu.main.params]
  icon = "x-twitter"

[services.googleAnalytics]
ID = "G-MEASUREMENT_ID"

[params]
enableInlineShortcodes = true

  [params.page]
  width = "full"

  [params.navbar]
  displayTitle = false
  displayLogo = true

    [params.navbar.logo]
    path = "images/logo_black.png"
    dark = "images/logo_white.png"
    link = "/"
    width = 120
    height = 20

  [params.footer]
  displayCopyright = true
  displayPoweredBy = false
  enableFooterSwitches = false
  width = "full"

  [params.editURL]
  enable = true
  base = "https://github.com/uthoplatforms/utho-docs/edit/main/content"

  [params.comments]
  enable = true
  type = "giscus"

  [params.giscus]
  repo = "<repository>"
  repoId = "<repository ID>"
  category = "<category>"
  categoryId = "<category ID>"